services:
  eazyscenes.web:
    image: eazyscenes.web
    container_name: EazyScenes.Web
    build:
      context: .
      dockerfile: EazyScenes.Web/Dockerfile
  
  eazyscenes.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: EazyScenes.DB
    environment:
      SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"
    volumes:
      - ./.containers/database:/var/lib/sqlserver/data
    ports:
      - "1433:1433"