@EazyScenes.Web_HostAddress = https://localhost:7218

GET {{EazyScenes.Web_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{EazyScenes.Web_HostAddress}}/users/69
Accept: application/json

###

POST {{EazyScenes.Web_HostAddress}}/users/
Accept: application/json
###

POST {{EazyScenes.Web_HostAddress}}/testpost
Content-Type: application/x-www-form-urlencoded

{
"username":"test",
"password":"password123!"
}